CREATE TABLE [dbo].[TPITOSRedFlags]
(
[TPITOSRedFlagsPK] [int] NOT NULL IDENTITY(1, 1),
[Creator] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreateDate] [datetime] NOT NULL,
[TPITOSFK] [int] NOT NULL,
[RedFlagCodeFK] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPITOSRedFlags] ADD CONSTRAINT [PK_TPITOSRedFlags] PRIMARY KEY CLUSTERED  ([TPITOSRedFlagsPK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPITOSRedFlags] ADD CONSTRAINT [FK_TPITOSRedFlags_CodeTPITOSRedFlag] FOREIGN KEY ([RedFlagCodeFK]) REFERENCES [dbo].[CodeTPITOSRedFlag] ([CodeTPITOSRedFlagPK])
GO
ALTER TABLE [dbo].[TPITOSRedFlags] ADD CONSTRAINT [FK_TPITOSRedFlags_TPITOS] FOREIGN KEY ([TPITOSFK]) REFERENCES [dbo].[TPITOS] ([TPITOSPK])
GO
