CREATE TABLE [dbo].[BenchmarkOfQualityFCCChanged]
(
[BenchmarkOfQualityFCCChangedPK] [int] NOT NULL IDENTITY(1, 1),
[ChangeDatetime] [datetime] NOT NULL,
[ChangeType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Deleter] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BenchmarkOfQualityFCCPK] [int] NOT NULL,
[Creator] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreateDate] [datetime] NOT NULL,
[Editor] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditDate] [datetime] NULL,
[FormDate] [datetime] NOT NULL,
[Indicator1] [int] NULL,
[Indicator2] [int] NULL,
[Indicator3] [int] NULL,
[Indicator4] [int] NULL,
[Indicator5] [int] NULL,
[Indicator6] [int] NULL,
[Indicator7] [int] NULL,
[Indicator8] [int] NULL,
[Indicator9] [int] NULL,
[Indicator10] [int] NULL,
[Indicator11] [int] NULL,
[Indicator12] [int] NULL,
[Indicator13] [int] NULL,
[Indicator14] [int] NULL,
[Indicator15] [int] NULL,
[Indicator16] [int] NULL,
[Indicator17] [int] NULL,
[Indicator18] [int] NULL,
[Indicator19] [int] NULL,
[Indicator20] [int] NULL,
[Indicator21] [int] NULL,
[Indicator22] [int] NULL,
[Indicator23] [int] NULL,
[Indicator24] [int] NULL,
[Indicator25] [int] NULL,
[Indicator26] [int] NULL,
[Indicator27] [int] NULL,
[Indicator28] [int] NULL,
[Indicator29] [int] NULL,
[Indicator30] [int] NULL,
[Indicator31] [int] NULL,
[Indicator32] [int] NULL,
[Indicator33] [int] NULL,
[Indicator34] [int] NULL,
[Indicator35] [int] NULL,
[Indicator36] [int] NULL,
[Indicator37] [int] NULL,
[Indicator38] [int] NULL,
[Indicator39] [int] NULL,
[Indicator40] [int] NULL,
[Indicator41] [int] NULL,
[Indicator42] [int] NULL,
[Indicator43] [int] NULL,
[Indicator44] [int] NULL,
[Indicator45] [int] NULL,
[Indicator46] [int] NULL,
[Indicator47] [int] NULL,
[IsComplete] [bit] NOT NULL CONSTRAINT [DF_BenchmarkOfQualityFCCChanged_IsComplete] DEFAULT ((1)),
[TeamMembers] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VersionNumber] [int] NOT NULL CONSTRAINT [DF_BenchmarkOfQualityFCCChanged_VersionNumber] DEFAULT ((1)),
[ProgramFK] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BenchmarkOfQualityFCCChanged] ADD CONSTRAINT [PK_BenchmarkOfQualityFCCChanged] PRIMARY KEY CLUSTERED ([BenchmarkOfQualityFCCChangedPK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BenchmarkOfQualityFCCChanged_BenchmarkOfQualityFCCPK_ChangeDatetime] ON [dbo].[BenchmarkOfQualityFCCChanged] ([BenchmarkOfQualityFCCPK], [ChangeDatetime] DESC) ON [PRIMARY]
GO
