CREATE TABLE [dbo].[TPOTRedFlags]
(
[TPOTRedFlagsPK] [int] NOT NULL IDENTITY(1, 1),
[Creator] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreateDate] [datetime] NOT NULL,
[TPOTFK] [int] NOT NULL,
[RedFlagCodeFK] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPOTRedFlags] ADD CONSTRAINT [PK_TPOTRedFlags] PRIMARY KEY CLUSTERED  ([TPOTRedFlagsPK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPOTRedFlags] ADD CONSTRAINT [FK_TPOTRedFlags_CodeTPOTRedFlag] FOREIGN KEY ([RedFlagCodeFK]) REFERENCES [dbo].[CodeTPOTRedFlag] ([CodeTPOTRedFlagPK])
GO
ALTER TABLE [dbo].[TPOTRedFlags] ADD CONSTRAINT [FK_TPOTRedFlags_TPOT] FOREIGN KEY ([TPOTFK]) REFERENCES [dbo].[TPOT] ([TPOTPK])
GO
