CREATE TABLE [dbo].[TPITOSChanged]
(
[TPITOSChangedPK] [int] NOT NULL IDENTITY(1, 1),
[ChangeDatetime] [datetime] NOT NULL,
[ChangeType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TPITOSPK] [int] NOT NULL,
[ClassroomRedFlagsNumPossible] [int] NULL,
[ClassroomRedFlagsNumYes] [int] NULL,
[Creator] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreateDate] [datetime] NOT NULL,
[Editor] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditDate] [datetime] NULL,
[IsValid] [bit] NOT NULL,
[Item1NumNo] [int] NULL,
[Item1NumYes] [int] NULL,
[Item2NumNo] [int] NULL,
[Item2NumYes] [int] NULL,
[Item3NumNo] [int] NULL,
[Item3NumYes] [int] NULL,
[Item4NumNo] [int] NULL,
[Item4NumYes] [int] NULL,
[Item5NumNo] [int] NULL,
[Item5NumYes] [int] NULL,
[Item6NumNo] [int] NULL,
[Item6NumYes] [int] NULL,
[Item7NumNo] [int] NULL,
[Item7NumYes] [int] NULL,
[Item8NumNo] [int] NULL,
[Item8NumYes] [int] NULL,
[Item9NumNo] [int] NULL,
[Item9NumYes] [int] NULL,
[Item10NumNo] [int] NULL,
[Item10NumYes] [int] NULL,
[Item11NumNo] [int] NULL,
[Item11NumYes] [int] NULL,
[Item12NumNo] [int] NULL,
[Item12NumYes] [int] NULL,
[Item13NumNo] [int] NULL,
[Item13NumYes] [int] NULL,
[LeadTeacherRedFlagsNumYes] [int] NULL,
[LeadTeacherRedFlagsNumPossible] [int] NULL,
[Notes] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumAdultsBegin] [int] NOT NULL,
[NumAdultsEnd] [int] NOT NULL,
[NumAdultsEntered] [int] NOT NULL,
[NumKidsBegin] [int] NOT NULL,
[NumKidsEnd] [int] NOT NULL,
[ObservationEndDateTime] [datetime] NOT NULL,
[ObservationStartDateTime] [datetime] NOT NULL,
[OtherTeacherRedFlagsNumYes] [int] NULL,
[OtherTeacherRedFlagsNumPossible] [int] NULL,
[ClassroomFK] [int] NOT NULL,
[ObserverFK] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPITOSChanged] ADD CONSTRAINT [PK_TPITOSChanged] PRIMARY KEY CLUSTERED  ([TPITOSChangedPK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TPITOSChanged_TPITOSPK_ChangeDatetime] ON [dbo].[TPITOSChanged] ([TPITOSPK], [ChangeDatetime] DESC) ON [PRIMARY]
GO
