CREATE TABLE [dbo].[BenchmarkOfQualityCWLTChanged]
(
[BenchmarkOfQualityCWLTChangedPK] [int] NOT NULL IDENTITY(1, 1),
[ChangeDatetime] [datetime] NOT NULL,
[ChangeType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Deleter] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BenchmarkOfQualityCWLTPK] [int] NOT NULL,
[Creator] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreateDate] [datetime] NOT NULL,
[Editor] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EditDate] [datetime] NULL,
[FormDate] [datetime] NOT NULL,
[Indicator1] [int] NOT NULL,
[Indicator2] [int] NOT NULL,
[Indicator3] [int] NOT NULL,
[Indicator4] [int] NOT NULL,
[Indicator5] [int] NOT NULL,
[Indicator6] [int] NOT NULL,
[Indicator7] [int] NOT NULL,
[Indicator8] [int] NOT NULL,
[Indicator9] [int] NOT NULL,
[Indicator10] [int] NOT NULL,
[Indicator11] [int] NOT NULL,
[Indicator12] [int] NOT NULL,
[Indicator13] [int] NOT NULL,
[Indicator14] [int] NOT NULL,
[Indicator15] [int] NOT NULL,
[Indicator16] [int] NOT NULL,
[Indicator17] [int] NOT NULL,
[Indicator18] [int] NOT NULL,
[Indicator19] [int] NOT NULL,
[Indicator20] [int] NOT NULL,
[Indicator21] [int] NOT NULL,
[Indicator22] [int] NOT NULL,
[Indicator23] [int] NOT NULL,
[Indicator24] [int] NOT NULL,
[Indicator25] [int] NOT NULL,
[Indicator26] [int] NOT NULL,
[Indicator27] [int] NOT NULL,
[Indicator28] [int] NOT NULL,
[Indicator29] [int] NOT NULL,
[Indicator30] [int] NOT NULL,
[Indicator31] [int] NOT NULL,
[Indicator32] [int] NOT NULL,
[Indicator33] [int] NOT NULL,
[Indicator34] [int] NOT NULL,
[Indicator35] [int] NOT NULL,
[Indicator36] [int] NOT NULL,
[Indicator37] [int] NOT NULL,
[Indicator38] [int] NOT NULL,
[Indicator39] [int] NOT NULL,
[HubFK] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BenchmarkOfQualityCWLTChanged] ADD CONSTRAINT [PK_BenchmarkOfQualityCWLTChanged] PRIMARY KEY CLUSTERED ([BenchmarkOfQualityCWLTChangedPK]) ON [PRIMARY]
GO
